name = "nextjs-cloudflare-demo"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages build output directory
pages_build_output_dir = ".next/static"

[build]
command = "npm run build"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]
